language: go
go:
  - 1.12.x

env:
  global:
    - GO111MODULE=on

install:
  - curl -sL https://git.io/goreleaser | head -n -2 | bash
  - tar -xf /tmp/goreleaser.tar.gz -C $GOPATH/bin
  - goreleaser -v

script:
  - go test ./...
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      goreleaser release --skip-publish
    else
      goreleaser release --snapshot
    fi

deploy:
  provider: releases
  api_key:
    secure: Kfb2+RBJI178gF605QvVHQN1LSMcGcVaF9rCA8ip/HAaoPkYbuHohog4QF2H4uLbeXohQzmtB2sKVp/By4aMxAvp4xpQ4rB1NKJFndS8tmeTVWQuy6V694irPGmEgvxL/6Y7XWWaeY7QZ4+cRloQ2Y9UnNPhP2etn9JHhiS3rYY=
  file_glob: true
  file:
    - dist/checksums.txt
    - dist/*.tar.gz
    - dist/*.zip
  skip_cleanup: true
  draft: true
  on:
    tags: true

notifications:
  email:
    recipients:
      - travisci@crazymax.dev
    on_success: always
    on_failure: always
