name: Bug Report
description: Report a bug

body:

  - type: checkboxes
    attributes:
      label: Contributing guidelines
      description: Please read the contributing guidelines before proceeding.
      options:
        - label: I've read the [contributing guidelines](https://github.com/crazy-max/ftpgrab/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree
          required: true

  - type: checkboxes
    attributes:
      label: I've found a bug and checked that ...
      description: Make sure that your request fulfills all of the following requirements. If one requirement cannot be satisfied, explain in detail why.
      options:
        - label: ... the documentation does not mention anything about my problem
        - label: ... there are no open or closed issues that are related to my problem

  - type: textarea
    attributes:
      label: Description
      description: Please provide a brief description of the bug in 1-2 sentences.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behaviour
      description: Please describe precisely what you'd expect to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual behaviour
      description: Please describe precisely what is actually happening.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please describe the steps to reproduce the bug.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Version
      description: Please provide FTPGrab, operating system version and system infirmation.
      value: |
        * FTPGrab version (5.0.0):
        * Platform (windows/linux/freebsd/macos):
        * System info (type `uname -a`):
        * Remote FTP (Pure-FTPd) or SFTP (OpenSSH) server:
    validations:
      required: true

  - type: textarea
    attributes:
      label: Configuration
      description: Please provide a minimal (!) [`ftpgrab.yml` config](https://crazymax.dev/ftpgrab/config/) to reproduce the bug.
      placeholder: |
        server:
          ftp:
            host: test.rebex.net
            port: 21
            username: demo
            password: password
            sources:
              - /
        download:
          output: /download
      render: yaml
    validations:
      required: true

  - type: textarea
    attributes:
      label: Logs
      description: Please provide FTPGrab logs (set `--log-level debug` and `--log-ftp`).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional info
      description: Please provide additional information.
